  name: islamiat
  description: "A new Flutter project."
  publish_to: 'none' # Remove this line if you wish to publish to pub.dev
  version: 1.0.0+1
  environment:
    sdk: '>=3.3.4 <4.0.0'
  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.6

  dev_dependencies:
    flutter_native_splash: ^2.4.0
    flutter_test:
      sdk: flutter
    flutter_lints: ^3.0.0

  flutter_native_splash:
    background_image: assets/images/splash_screen.png  # Path to the splash screen image
    background_image_dark: assets/images/splash_image_night.png
    android: true  # Enable splash screen for Android
    ios: true  # Enable splash screen for iOS
    web: false  # Enable splash screen for Web (if needed)
    android_gravity: fill  # Position of the image on the splash screen
    ios_content_mode: scaleToFill
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
  flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
    uses-material-design: true

  # To add assets to your application, add an assets section, like this:
    assets:
      - assets/
      - assets/images/
      - assets/files/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages